import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/header/Navbar";
import Sidebar from "@/components/header/Sidebar";
import { SidebarProvider } from "@/context/SidebarContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className= "antialiased font-actay bg-[#040c15]"
      >
       <SidebarProvider>
         <div className="flex flex-col h-screen overflow-hidden">
           <Navbar />
          <div className="flex flex-1 overflow-hidden">
            <Sidebar />
            <main className="flex-1 overflow-auto bg-[#000000BF] text-white">{children}</main>
          </div>
         </div>
        </SidebarProvider>
      </body>
      
    </html>
  );
}
