import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/Navbar";
import Sidebar from "@/components/header/Sidebar";
import { SidebarProvider } from "@/context/SidebarContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased flex justify-center`}
      >
        <SidebarProvider>
         <div className="flex flex-col h-screen overflow-hidden max-w-[1900px]">
           <Navbar />
          <div className="flex flex-1 overflow-hidden">
            <Sidebar />
            <main className="flex-1 overflow-auto bg-[#0a082d] text-white p-4">{children}</main>
          </div>
         </div>
        </SidebarProvider>
      </body>
      
    </html>
  );
}
